---
Name: silverstripe-mapboxfield
---
Bigfork\SilverStripeMapboxField\MapboxField:
  access_token: ''
  api_css_url: 'https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css'
  api_javascript_url: 'https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js'
  geocoder_css_url: 'https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css'
  geocoder_javascript_url: 'https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js'
  map_style: 'mapbox://styles/mapbox/basic-v9'
SilverStripe\Admin\LeftAndMain:
  extensions:
    - 'Bigfork\SilverStripeMapboxField\LeftAndMainExtension'
  extra_requirements_javascript:
    - 'bigfork/silverstripe-mapboxfield:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'bigfork/silverstripe-mapboxfield:client/dist/styles/bundle.css'
